export const FETCH_SHOW_CAST_REQUEST = 'FETCH_SHOW_CAST_REQUEST';
export const FETCH_SHOW_CAST_SUCCESS = 'FETCH_SHOW_CAST_SUCCESS'; 
export const FETCH_SHOW_CAST_FAILURE = 'FETCH_SHOW_CAST_FAILURE';


export const FETCH_SHOW_DETAILS_REQUEST = 'FETCH_SHOW_DETAILS_REQUEST';
export const FETCH_SHOW_DETAILS_SUCCESS = 'FETCH_SHOW_DETAILS_SUCCESS'; 
export const FETCH_SHOW_DETAILS_FAILURE = 'FETCH_SHOW_DETAILS_FAILURE';
